// Listado de todos los archivos a incluir en el codigo fuente...
#ifndef INCLUIR_H
#define INCLUIR_H

#include "angulo.h"
#include "clima.h"
#include "config.h"
#include "datahead.h"
#include "disparos.h"
#include "efectos1.h"
#include "explos.h"
#include "game.h"
#include "incluir.h"
#include "k_gui.h"
#include "luces.h"
#include "mapluz.h"
#include "menues.h"
#include "pc_ia.h"
#include "poligono.h"
#include "premios.h"
#include "principa.h"
#include "sonido.h"
#include "startgam.h"
#include "tablero.h"
#include "tanques.h"
#include "videom.h"
#include "angulo.c"
#include "clima.c"
#include "config.c"
#include "disparos.c"
#include "efectos1.c"
#include "explos.c"
#include "game.c"
#include "k_gui.c"
#include "luces.c"
#include "mapluz.c"
#include "menues.c"
#include "pc_ia.c"
#include "poligono.c"
#include "premios.c"
#include "sonido.c"
#include "startgam.c"
#include "tablero.c"
#include "tanques.c"

#endif
